__default__:
    runtime: 10
    cores: 1
    memory: 16000
    output: "build/logs/{rule}.{wildcards}.log"
    name: "{rule}.{wildcards}"
run_national:
    runtime: 1439
    cores: 6
    memory: 10000
run_regional:
    runtime: 5760
    cores: 6
    memory: 45000
national_uncertainty_run:
    runtime: 120
    cores: 6
    memory: 5000
    output: "build/logs/uncertainty/{rule}.{wildcards}.log"
regional_uncertainty_run:
    runtime: 5760
    cores: 6
    memory: 45000
    output: "build/logs/uncertainty/{rule}.{wildcards}.log"
weather_run:
    runtime: 1439
    cores: 6
    memory: 30000
run_single_location:
    runtime: 60
y:
    output: "build/logs/uncertainty/{rule}.{wildcards}.log"
plot_map:
    runtime: 60
test:
    runtime: 120
    memory: 128000
test_uncertainty_runs:
    runtime: 240
    memory: 128000
overview_cost_assumptions:
    runtime: 60
aggregated_results:
    runtime: 60
    memory: 128000
time_aggregated_results:
    runtime: 30
    memory: 48000
