__default__:
    runtime: 10
    cores: 1
    memory: 16000
    output: "build/logs/{rule}.{wildcards}.log"
run_national:
    runtime: 1439
    cores: 4
    memory: 16000
run_regional:
    runtime: 2879
    cores: 4
    memory: 48000
performance_run:
    runtime: 1439
    cores: 16
    memory: 16000
