__default__:
    runtime: 10
    cores: 1
    memory: 16000
    output: "build/logs/{rule}.{wildcards}.log"
run_national:
    runtime: 1439
    cores: 6
    memory: 10000
run_regional:
    runtime: 2879
    cores: 6
    memory: 40000
uncertainty_run:
    runtime: 120
    cores: 6
    memory: 5000
weather_run:
    runtime: 2879
    cores: 6
    memory: 40000
run_single_location:
    runtime: 60
plot_map:
    runtime: 60
test:
    runtime: 60
    memory: 128000
overview_cost_assumptions:
    runtime: 60
aggregated_results:
    runtime: 60
    memory: 128000
