__default__:
    runtime: 10
    cores: 1
    memory: 16000
    output: "build/logs/{rule}.{wildcards}.log"
run_national:
    runtime: 1439
    cores: 6
    memory: 10000
run_regional:
    runtime: 2879
    cores: 6
    memory: 40000
plot_map:
    runtime: 60
