scaling-factors:
    power: 0.001 # from MW to GW
    area: 0.001 # from km to 1000 km2
    monetary: 0.000001 # from EUR to Mio EUR
scenarios:
    # - continental-autarky-strict FIXME currently broken due to https://github.com/calliope-project/calliope/issues/227
    # - national-autarky-strict FIXME currently broken due to https://github.com/calliope-project/calliope/issues/227
    - national-autarky-weak85
    - national-autarky-weak70
