scaling-factors:
    power: 0.00001 # from MW to 100 GW
    area: 0.0001 # from km to 10000 km2
    monetary: 0.000000001 # from EUR to 1000 Mio EUR
capacity-factors:
    min: 0.001 # consider smaller values to be 0; this helps numerics in the LP
    max: 10 # for hydro reservoirs, value chosen so that numerical range is << 1e6
            # considering a time resolution of 4 H (0.001 - 10*4=40)
parameters:
    biofuel-efficiency: 0.45
    jrc-biofuel:
        scenario: medium
resolution:
    space: national
    time: 1M
subset_time: "['2016-01-01', '2016-12-31']"
year: 2016
scenarios:
    - continental-autarky-100-continental-grid
    - national-autarky-100-continental-grid
    - national-autarky-100-national-grid
    - national-autarky-85-continental-grid
    - national-autarky-70-continental-grid
    - regional-autarky-100-continental-grid
    - regional-autarky-100-national-grid
    - regional-autarky-100-regional-grid
    - regional-autarky-85-continental-grid
    - regional-autarky-85-national-grid
    - regional-autarky-70-continental-grid
    - regional-autarky-70-national-grid
connected-regions: # regions with insufficient potentials can be connected to neighbours
    AUT-9_1: AUT-3_1 # Vienna: Lower Austria
    BEL-1_1: BEL-2_1 # Bruxelles: Flanders
    DEU-3_1: DEU-4_1 # Berlin: Brandenburg
    NOR-12_1: NOR-1_1 # Oslo: Akershus
    CHE-5_1: CHE-4_1 # Basel-City: Basel-Country
weather-uncertainty:
    start-year: 2012
    resolution:
        space: national
        time: 1M
    scenarios:
        large-scale: continental-autarky-100-continental-grid
        small-scale: national-autarky-100-national-grid
uncertainty:
    experiment-design: ./config/uncertainty-experiment-design-small.tsv
    resolution:
        space: national
        time: 1M
    subset_time: "['2016-01-01', '2016-12-31']"
    scenarios:
        large-scale: continental-autarky-100-continental-grid
        small-scale: national-autarky-100-national-grid
    parameters:
        depreciation-rate:
            short-name: d_r
            description: System- and sector-wide depreciation rate of investments.
            min: 0.016
            max: 0.138
            unit: "-/yr"
            source: "max and min for solar and wind between 2009 and 2017 in @Steffen:2019"
            scaling-factor:
            inverse-scaling-factor:
            calliope-params:
                tech_groups.conversion.costs.monetary.interest_rate: 1
                tech_groups.conversion_plus.costs.monetary.interest_rate: 1
                tech_groups.storage.costs.monetary.interest_rate: 1
                tech_groups.supply.costs.monetary.interest_rate: 1
                tech_groups.supply_plus.costs.monetary.interest_rate: 1
                tech_groups.transmission.costs.monetary.interest_rate: 1
        installation-cost-pv:
            short-name: c_pv
            description: Costs for installing photovoltaics capacity.
            min: 280_000
            max: 580_000
            unit: EUR/MW
            source: "[@JRC:2014] (Table 7)"
            scaling-factor: monetary
            inverse-scaling-factor: power
            calliope-params:
                tech_groups.pv.costs.monetary.energy_cap: 1
                tech_groups.pv.costs.monetary.om_annual: 0.017
                # TODO do something about om_prod missing
        installation-cost-wind-onshore:
            short-name: c_wind
            description: Costs for installing onshore wind capacity.
            min: 800_000
            max: 1_700_000
            unit: EUR/MW
            source: "[@JRC:2014] (Table 4)"
            scaling-factor: monetary
            inverse-scaling-factor: power
            calliope-params:
                tech_groups.wind_onshore.costs.monetary.energy_cap: 1
                tech_groups.wind_onshore.costs.monetary.om_annual: 0.017
                # TODO do something about om_prod missing
        installation-cost-wind-offshore:
            short-name: c_offshore
            description: Costs for installing offshore wind capacity.
            min: 1_790_000
            max: 3_270_000
            unit: EUR/MW
            source: "[@JRC:2014] (Table 5)"
            scaling-factor: monetary
            inverse-scaling-factor: power
            calliope-params:
                techs.wind_offshore.costs.monetary.energy_cap: 1
                techs.wind_offshore.costs.monetary.om_annual: 0.023
                # TODO do something about om_prod missing
        installation-cost-short-term-storage-power:
            short-name: c_sts_p
            description: Costs for installing battery power capacity (inverter etc.).
            min: 31_000
            max: 141_000
            unit: EUR/MW
            source: "[@Schmidt:2019]"
            scaling-factor: monetary
            inverse-scaling-factor: power
            calliope-params:
                techs.battery.costs.monetary.energy_cap: 1
        installation-cost-short-term-storage-energy:
            short-name: c_sts_e
            description: Costs for installing battery energy capacity.
            min: 36_000
            max: 166_000
            unit: EUR/MWh
            source: "[@Schmidt:2019]"
            scaling-factor: monetary
            inverse-scaling-factor: power
            calliope-params:
                techs.battery.costs.monetary.storage_cap: 1
        installation-cost-long-term-storage-power:
            short-name: c_lts_p
            description: Costs for installing hydrogen power capacity (fuel cell etc.).
            min: 1_123_000
            max: 2_100_000
            unit: EUR/MW
            source: "[@Schmidt:2019]"
            scaling-factor: monetary
            inverse-scaling-factor: power
            calliope-params:
                techs.hydrogen.costs.monetary.energy_cap: 1
        installation-cost-long-term-storage-energy:
            short-name: c_lts_e
            description: Costs for installing hydrogen energy capacity.
            min: 6_000
            max: 12_000
            unit: EUR/MWh
            source: "[@Schmidt:2019]"
            scaling-factor: monetary
            inverse-scaling-factor: power
            calliope-params:
                techs.hydrogen.costs.monetary.storage_cap: 1
        installation-cost-ntc:
            short-name: c_ntc
            description: Costs for installing net transfer capacity (high voltage ac transmission).
            min: 0.7
            max: 1.08
            unit: EUR/MW/m
            source: "[@JRC:2014] (Table 39)"
            scaling-factor: monetary
            inverse-scaling-factor: power
            calliope-params:
                techs.ac_transmission.costs.monetary.energy_cap_per_distance: 1
        installation-cost-biofuel:
            short-name: c_bio
            description: Costs for installing biofuel capacities.
            min: 1_380_000
            max: 3_450_000
            unit: EUR/MW
            source: "[@JRC:2014](Table 48)"
            scaling-factor: monetary
            inverse-scaling-factor: power
            calliope-params:
                techs.biofuel.costs.monetary.energy_cap: 1
                techs.biofuel.costs.monetary.om_annual: 0.041
        fuel-cost-biofuel: # FIXME actually not independent, but varies together with `availability-biofuel`.
            short-name: c_fuel
            description: Fuel costs biofuel (includes combustion efficiency and variable generation costs).
            min: 28.12 # includes 3.1 om_gen costs
            max: 33.68 # includes 3.1 om_gen costs
            unit: EUR/MWh
            source: "[@RuizCastello:2015]"
            scaling-factor: monetary
            inverse-scaling-factor: power
            calliope-params:
                techs.biofuel.costs.monetary.om_con: 1
        availability-biofuel:
            short-name: a_bio
            description: Interpolation between biofuel potential scenarios.
            min: 0 # represents low availability scenario
            max: 1 # represents high availability scenario
            unit: "-"
            source: "[@RuizCastello:2015]"
            scaling-factor:
            inverse-scaling-factor:
            calliope-params: # handled as special case in code
sea-connections:
    continental:
    national:
        - [ITA, GRC]
        - [EST, FIN]
        - [SWE, LTU]
        - [SWE, POL]
        - [DNK, SWE]
        - [SWE, DEU]
        - [NOR, DNK]
        - [NOR, DEU]
        - [NOR, NLD]
        - [NOR, GBR]
        - [FIN, SWE]
        - [GBR, FRA]
        - [GBR, BEL]
        - [GBR, NLD]
        - [GBR, IRL]
    regional:
        - [ESP.7_1, ESP.1_1] # Ceuta and Andalucia
        - [ESP.13_1, ESP.10_1] # Islas Baleares and Comunidad Valenciana
        - [FRA.5_1, ITA.16_1] # Corse and Toscana
        - [FRA.5_1, ITA.14_1] # Corse and Sardegna
        - [ITA.14_1, ITA.8_1] # Sardegna and Lazio
        - [ITA.4_1, ITA.15_1] # Calabria and Sicily
        - [ITA.2_1, GRC.5_1] # Apulia and Epirus and Western Macedonia
        - [GRC.7_1, GRC.4_1] # Peloponnese, Western Greece and the Ionian Islands and Crete
        - [GRC.3_1, GRC.1_1] # Attica and Aegean
        - [EST.1_1, FIN.4_1] # Harju and Southern Finland
        - [SWE.8_1, LTU.3_1] # Kalmar and Klaipedos
        - [SWE.8_1, SWE.4_1] # Kalmar and Gotland
        - [SWE.1_1, POL.11_1] # Blekinge and Pomorskie
        - [DNK.1_1, SWE.13_1] # Hovedstaden and Skåne
        - [SWE.13_1, DEU.15_1] # Skåne and Schleswig-Holstein
        - [DNK.4_1, DEU.8_1] # Sjælland and Mecklenburg-Vorpommern
        - [DNK.4_1, DNK.5_1] # Sjælland and Syddanmark
        - [DNK.3_1, SWE.12_1] # Nordjylland and Östergötland
        - [NOR.18_1, DNK.3_1] # Vest-Agder and Nordjylland
        - [NOR.18_1, DEU.15_1] # Vest-Agder and Schleswig-Holstein
        - [NOR.18_1, NLD.5_1] # Vest-Agder and Groningen
        - [NOR.13_1, GBR.1_1] # Rogaland and England
        - [FIN.5_1, SWE.16_1] # Western Finland and Uppsala
        - [GBR.1_1, FRA.7_1] # England and Hauts-de-France
        - [GBR.1_1, BEL.2_1] # England and Vlaanderen
        - [GBR.1_1, NLD.14_1] # England and Zuid-Holland
        - [GBR.4_1, IRL.17_1] # Wales and Meath
        - [GBR.3_1, GBR.2_1] # Scotland and Northern Ireland
        # the following do not exist today
        - [EST.7_1, EST.2_1] # Lääne and Hiiu
        - [EST.7_1, EST.12_1] # Lääne and Saare
scope:
    countries:
        - "Austria"
        - "Belgium"
        - "Bulgaria"
        - "Croatia"
        - "Czech Republic"
        - "Denmark"
        - "Estonia"
        - "Finland"
        - "France"
        - "Germany"
        - "Greece"
        - "Hungary"
        - "Ireland"
        - "Italy"
        - "Latvia"
        - "Lithuania"
        - "Luxembourg"
        - "Netherlands"
        - "Poland"
        - "Portugal"
        - "Romania"
        - "Slovakia"
        - "Slovenia"
        - "Spain"
        - "Sweden"
        - "United Kingdom"
        - "Albania"
        - "Bosnia and Herzegovina"
        - "Macedonia, Republic of"
        - "Montenegro"
        - "Norway"
        - "Serbia"
        - "Switzerland"
    bounds:
        x_min: -15.8 # in degrees east
        x_max: 37  # in degrees east
        y_min: 30  # in degrees north
        y_max: 75  # in degrees north
shapes: # This config must be consistent with data from https://doi.org/10.5281/zenodo.3244985.
    continental:
        Austria: nuts0
        Belgium: nuts0
        Bulgaria: nuts0
        Croatia: nuts0
        Czech Republic: nuts0
        Denmark: nuts0
        Estonia: nuts0
        Finland: nuts0
        France: nuts0
        Germany: nuts0
        Greece: nuts0
        Hungary: nuts0
        Ireland: nuts0
        Italy: nuts0
        Latvia: nuts0
        Lithuania: nuts0
        Luxembourg: nuts0
        Netherlands: nuts0
        Poland: nuts0
        Portugal: nuts0
        Romania: nuts0
        Slovakia: nuts0
        Slovenia: nuts0
        Spain: nuts0
        Sweden: nuts0
        United Kingdom: nuts0
        Albania: gadm0
        Bosnia and Herzegovina: gadm0
        Macedonia, Republic of: gadm0
        Montenegro: gadm0
        Norway: nuts0
        Serbia: gadm0
        Switzerland: nuts0
    national:
        Austria: nuts0
        Belgium: nuts0
        Bulgaria: nuts0
        Croatia: nuts0
        Czech Republic: nuts0
        Denmark: nuts0
        Estonia: nuts0
        Finland: nuts0
        France: nuts0
        Germany: nuts0
        Greece: nuts0
        Hungary: nuts0
        Ireland: nuts0
        Italy: nuts0
        Latvia: nuts0
        Lithuania: nuts0
        Luxembourg: nuts0
        Netherlands: nuts0
        Poland: nuts0
        Portugal: nuts0
        Romania: nuts0
        Slovakia: nuts0
        Slovenia: nuts0
        Spain: nuts0
        Sweden: nuts0
        United Kingdom: nuts0
        Albania: gadm0
        Bosnia and Herzegovina: gadm0
        Macedonia, Republic of: gadm0
        Montenegro: gadm0
        Norway: nuts0
        Serbia: gadm0
        Switzerland: nuts0
    regional:
        # The link between NUTS and administrative units unfortunately is not obvious.
        # It's not documented anywhere -- at least I could not find any information.
        # Hence, I am using GADM here instead.
        # Validation source: https://en.wikipedia.org/wiki/List_of_administrative_divisions_by_country
        Austria: gadm1 # gadm1 and wiki match 9
        Belgium: gadm1 # match 3
        Bulgaria: gadm1 # match 28
        Croatia: gadm1 # match 21
        Czech Republic: gadm1 # match 14
        Denmark: gadm1 # match 5
        Estonia: gadm1 # gadm1 16 regions; wiki 15 regions
        Finland: gadm1 # gadm1 5 regions; wiki 19 regions
        France: gadm1 # match 13
        Germany: gadm1 # match 16
        Greece: gadm1 # gadm1 8 regions; wiki 13 (14) regions
        Hungary: gadm1 # match 20
        Ireland: gadm1 # match 26
        Italy: gadm1 # match 20
        Latvia: gadm1 # gadm1 5 regions; wiki 119 regions
        Lithuania: gadm1 # match 10
        Luxembourg: gadm2 # match 12
        Netherlands: gadm1 # gadm1 14 regions; wiki 12 regions
        Poland: gadm1 # match 16
        Portugal: gadm1 # match 18
        Romania: gadm1 # match 42
        Slovakia: gadm1 # match 8
        Slovenia: gadm1 # match 12
        Spain: gadm1 # match 17
        Sweden: gadm1 # match 21
        United Kingdom: gadm1 # match 4
        Albania: gadm1 # match 12
        Bosnia and Herzegovina: gadm1 # match 3
        Macedonia, Republic of: nuts3 # match 8 (statistical, non-administrative)
        Montenegro: gadm1 # match 21
        Norway: gadm1 # match 19
        Serbia: gadm1 # gadm1 25 regions; wiki 5 regions
        Switzerland: gadm1 # match 26
