scaling-factors:
    power: 0.001 # from MW to GW
    area: 0.001 # from km to 1000 km2
    monetary: 0.00000001 # from EUR to 100 Mio EUR
minimal-capacity-factor: 0.001 # consider smaller values to be 0; this helps numerics in the LP
scenarios:
    - continental-autarky-100-continental-grid
    - national-autarky-100-continental-grid
    - national-autarky-100-national-grid
    - national-autarky-85-continental-grid
    - national-autarky-70-continental-grid
